# Generating Subs

#### Imports

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from openai_api import OpenAIAgent
import nest_asyncio
nest_asyncio.apply()
import os
import sys

# Add the parent directory (or another appropriate path) to sys.path so Python can find Exclusion_functions
notebook_dir = os.path.dirname(os.path.abspath('04_Optimization.ipynb'))
parent_dir = os.path.abspath(os.path.join(notebook_dir, '..', '..', '..'))
function_dir = os.path.abspath(os.path.join(parent_dir, 'Function_Files'))
if function_dir not in sys.path:
    sys.path.append(function_dir)
    
import Matching_functions as mf
import datetime

#### Variables

In [3]:
CATEGORY = "Cups"
today = datetime.datetime.now().strftime('%m.%d.%Y')
ip_path = f"{parent_dir}\\Data\\"
ip_path_cat = f"{parent_dir}\\Data\\{CATEGORY}\\"
OP_PATH = f"{parent_dir}\\Data\\{CATEGORY}\\Output\\"

In [4]:
im_final = pd.read_csv(f"{OP_PATH}{CATEGORY}_Attributed_non_printed.csv")

In [5]:
im_final.shape

(1653, 30)

#### Embeddings and Matches

In [6]:
im_final = mf.make_embeddings(im_final)

Starting make_embeddings...
Rows prepared for embedding: 1653

Embedding Batches: 100%|██████████| 17/17 [04:07<00:00, 14.53s/it]

Finished embedding generation.

In [7]:
im_final.head()

,Entity--Item,Item Desc 1,Item Desc 2,Qty,Gross Cost,Net Cost,po_cost_amt,VB Flag,VGN,VPN,...,Product Capacity,Compatible Product & Product Type,Bottom Diameter (IN),Top Diameter (IN),Product Dimension Type,Product Dimensions,Pattern & Design,Case Pack,for_embedding,embeddings
0,1--VBCLLH16DB,VB LID HOT CUP DOME BLK 92MM,PS 10 OZ SQUAT-24 OZ 20/50,10474,185100,185880,20.629195,Y - VB,Graphic Packaging,316873008,...,16 OZ,10 OZ Squat-24 OZ Cups,NaN,92MM,Standard Product Dimensions,NaN,VB LID HOT CUP DOME BLK 92MM PS 10 OZ SQUAT-24...,1000,Lid Lid Black Polystyrene (PS) Hot Only Yes ...,"[-0.008323983289301395, 0.016245974227786064, ..."
1,1--PTC09D92,VB CUP COLD 9 OZ SQUAT PET,92 SERIES CLR 20/50,15365,487038,339648,43.747324,Y - VB,"Carryout Bags, Inc.",VB-VG9OF,...,9 OZ,NaN,2.4,3.6,Tapered & Graduated Product Dimensions,3.6X2.8X2.4 IN,VB CUP COLD 9 OZ SQUAT PET 92 SERIES CLR 20/50,1000,Cup Cup Clear Polyethylene Terephthalate (PET)...,"[-0.02888156846165657, 0.028642995283007622, -..."
2,1--CPLUGBLACK,PLUG CIRCLE BLK FOR HOT CUP,LID SIP HOLE 5/400 BLACK,1507,37845,37845,24.190000,N,Amercareroyal,CPLUG-BK,...,NaN,Hot Cup Lid,NaN,NaN,NaN,NaN,PLUG CIRCLE BLK FOR HOT CUP LID SIP HOLE 5/400...,2000,Beverage Plug Beverage Plug 2000/Case Black Pl...,"[-0.0005539848352782428, -0.004044089466333389..."
3,1--2CUPCARRY,CARRIER HOLDER FOR 2 CUP,MOLDED FIBER 8-24 OZ,247,8645,8645,36.050000,Y - Other,"Carryout Bags, Inc.",2CUPCARRY,...,8-24 OZ,Cup,NaN,NaN,NaN,NaN,NaN,6000,Cup Carrier Without Tray Molded Fiber 8-2...,"[-0.006714086513966322, 0.02708226628601551, -..."
4,1--DLKC12/20NH,LID CUP COLD DOME CLR PET,W/ NO HOLE KAL-CLR,412,27053,15549,70.922743,N,Pactiv,000000000009508059,...,NaN,Cup,NaN,NaN,Standard Product Dimensions,3.8X1.6 IN,LID CUP COLD DOME CLR PET W/ NO HOLE KAL-CLR,1000,Lid Lid Clear Polyethylene Terephthalate (PET)...,"[-0.02185988612473011, 0.006927075330168009, -..."

In [8]:
im_final.columns

Index(['Entity--Item', 'Item Desc 1', 'Item Desc 2', 'Qty', 'Gross Cost',
       'Net Cost', 'po_cost_amt', 'VB Flag', 'VGN', 'VPN', 'Pack Size',
       'Combined Descriptions', 'Description with Attributes', 'attributes',
       'Beverage Cup Type', 'Product Type Collapse', 'Color', 'Material',
       'Foodservice Global Attributes', 'Usage Temperature',
       'Beverage Cup Style', 'Sustainable Products', 'Product Capacity',
       'Compatible Product & Product Type', 'Bottom Diameter (IN)',
       'Top Diameter (IN)', 'Product Dimension Type', 'Product Dimensions',
       'Pattern & Design', 'Case Pack', 'for_embedding', 'embeddings'],
      dtype='object')

In [9]:
user_prompts, idx_map = mf.get_user_prompts(im_final)

Generating Prompts: 100%|██████████| 1653/1653 [00:02<00:00, 643.70it/s]

In [10]:
count = 0
for user_prompt in user_prompts:
    count += 1
    print(user_prompt)
    print('----'*40)
    if count == 2:
        break

Original Item:
- Entity ID: 1

- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: Black,  Material: Polystyrene (PS),  Usage Temperature: Hot Only,  Sustainable Products: Yes,  Product Capacity: 16 OZ,  Product Dimension Type: Standard Product Dimensions, VB LID HOT CUP DOME BLK 92MM PS 10 OZ SQUAT-24 OZ 20/50
- VGN:
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: Black
- Material: Polystyrene (PS)
- Foodservice Global Attributes:
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products: Yes
- Product Capacity: 16 OZ
- Compatible Product & Product Type: 10 OZ Squat-24 OZ Cups
- Bottom Diameter (IN):
- Top Diameter (IN): 92MM
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions:
- Pattern & Design: VB LID HOT CUP DOME BLK 92MM PS 10 OZ SQUAT-24 OZ 20/50
- Case Pack: 1000

Top Similar Items from Descriptions:

- Entity ID: 16
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: White,  Material: Polystyrene (PS),  Usage Temperature: Hot Only,  Sustainable Products: Yes,  Product Capacity: 16 OZ,  Product Dimension Type: Standard Product Dimensions, VB LID HOT CUP DOME WHT 92MM PS 10 OZ SQUAT-24 OZ 20/50
- VGN: Graphic Packaging
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes:
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products: Yes
- Product Capacity: 16 OZ
- Compatible Product & Product Type: 10 OZ Squat-24 OZ Cups
- Bottom Diameter (IN):
- Top Diameter (IN): 92MM
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions:
- Pattern & Design: VB LID HOT CUP DOME WHT 92MM PS 10 OZ SQUAT-24 OZ 20/50
- Case Pack: 1000

- Entity ID: 1357
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: Black,  Material: Polystyrene (PS),  Usage Temperature: Hot Only,  Sustainable Products: Yes,  Product Capacity: 16 OZ,  Product Dimension Type: Standard Product Dimensions, VB LID HOT CUP FLAT BLK 92MM PS 10 OZ SQUAT-24 OZ 10/100
- VGN: Graphic Packaging
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Pack Size: 1000/Case
- Color: Black
- Material: Polystyrene (PS)
- Foodservice Global Attributes:
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products: Yes
- Product Capacity: 16 OZ
- Compatible Product & Product Type: 10 OZ Squat-24 OZ Cups
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions:
- Pattern & Design: VB LID HOT CUP FLAT BLK 92MM PS 10 OZ SQUAT-24 OZ 10/100
- Case Pack: 1000

- Entity ID: 522
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: White,  Material: Polystyrene (PS),  Usage Temperature: Hot Only,  Sustainable Products: Yes,  Product Capacity: 16 OZ,  Product Dimension Type: Standard Product Dimensions, VB LID HOT CUP FLAT WHT 92MM PS 10 OZ SQUAT-24 OZ 10/100
- VGN: Graphic Packaging
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes:
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products: Yes
- Product Capacity: 16 OZ
- Compatible Product & Product Type: 10 OZ SQUAT-24 OZ
- Bottom Diameter (IN):
- Top Diameter (IN): 92MM
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions:
- Pattern & Design: VB LID HOT CUP FLAT WHT 92MM PS 10 OZ SQUAT-24 OZ 10/100
- Case Pack: 1000

- Entity ID: 299
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: Black,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Product Capacity: 10-20 OZ,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions,  Product Dimensions: 3.7X0.7 IN, LID CUP HOT DOME BLK 10-20 OZ SOLO/CF BLACK
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: Black
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 10-20 OZ
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions: 3.7X0.7 IN
- Pattern & Design: LID CUP HOT DOME BLK 10-20 OZ SOLO/CF BLACK
- Case Pack: 1000

- Entity ID: 372
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: Black,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Product Capacity: 8 OZ,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions,  Product Dimensions: 3.2X0.7 IN, LID CUP DOME BLK PLASTIC 8 OZ SIP HOLE TRAVEL TRAVELER BLACK
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: Black
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 8 OZ
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions: 3.2X0.7 IN
- Pattern & Design: LID CUP DOME BLK PLASTIC 8 OZ SIP HOLE TRAVEL TRAVELER BLACK
- Case Pack: 1000

- Entity ID: 826
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: Black,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions,  Product Dimensions: 3.7X1 IN, LID CUP HOT DOME BLK RECLOSABLE BLACK
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: Black
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity:
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions: 3.7X1 IN
- Pattern & Design: LID CUP HOT DOME BLK RECLOSABLE BLACK
- Case Pack: 1000

- Entity ID: 695
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: White,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Product Capacity: 10 OZ,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions,  Product Dimensions: 3.4X0.7 IN, LID CUP HOT DOME WHT 10 OZ TRAVEL TALL SOLO WHITE
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 10 OZ
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions: 3.4X0.7 IN
- Pattern & Design: LID CUP HOT DOME WHT 10 OZ TRAVEL TALL SOLO WHITE
- Case Pack: 1000

- Entity ID: 357
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: White,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Product Capacity: 8 OZ,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions,  Product Dimensions: 3.2X0.7 IN, LID CUP HOT DOME WHT 8 OZ TRAVEL SOLO WHITE
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 8 OZ
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions: 3.2X0.7 IN
- Pattern & Design: LID CUP HOT DOME WHT 8 OZ TRAVEL SOLO WHITE
- Case Pack: 1000

- Entity ID: 597
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: White,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions,  Product Dimensions: 3.7X1 IN, LID CUP HOT DOME WHT RECLOSABLE WHITE
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity:
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions: 3.7X1 IN
- Pattern & Design: LID CUP HOT DOME WHT RECLOSABLE WHITE
- Case Pack: 1000

- Entity ID: 1466
- Description: VB LID CUP HOT FLAT PS WHT 80MM SERIES 10/100
- VGN: Graphic Packaging
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity:
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN): 3.1
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions:
- Pattern & Design: VB LID CUP HOT FLAT PS WHT 80MM SERIES 10/100
- Case Pack: 1000

- Entity ID: 10
- Description: Beverage Cup Type: Lid,  Product Type Collapse: Lid,  Pack Size: 1000/Case,  Color: White,  Material: Polystyrene (PS),  Foodservice Global Attributes: Disposable,  Usage Temperature: Hot Only,  Compatible Product & Product Type: Cup,  Product Dimension Type: Standard Product Dimensions, LID CUP HOT DOME WHT RECLOSABLE WHITE
- VGN: Dart
- Beverage Cup Type: Lid
- Product Type Collapse: Lid
- Color: White
- Material: Polystyrene (PS)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Hot Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity:
- Compatible Product & Product Type: Cup
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type: Standard Product Dimensions
- Product Dimensions:
- Pattern & Design: LID CUP HOT DOME WHT RECLOSABLE WHITE
- Case Pack: 1000


Return a list of Entity IDs that are swappable with the given Entity ID from the list of similar items, ordered by vendor preference (Victoria Bay > Preferred Vendors > Others).
If an item doesn't seem like it is swappable you can return None.
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Original Item:
- Entity ID: 2

- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 9 OZ,  Bottom Diameter (IN): 2.4,  Top Diameter (IN): 3.6,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.6X2.8X2.4 IN, VB CUP COLD 9 OZ SQUAT PET 92 SERIES CLR 20/50
- VGN:
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 9 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.4
- Top Diameter (IN): 3.6
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.6X2.8X2.4 IN
- Pattern & Design: VB CUP COLD 9 OZ SQUAT PET 92 SERIES CLR 20/50
- Case Pack: 1000

Top Similar Items from Descriptions:

- Entity ID: 17
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 12 OZ,  Bottom Diameter (IN): 2.4,  Top Diameter (IN): 3.6,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.6X4.2X2.4 IN, VB CUP COLD 12 OZ PET CLR 92MM SERIES 20/50
- VGN: Carryout Bags, Inc.
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 12 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.4
- Top Diameter (IN): 3.6
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.6X4.2X2.4 IN
- Pattern & Design: VB CUP COLD 12 OZ PET CLR 92MM SERIES 20/50
- Case Pack: 1000

- Entity ID: 65
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 10 OZ,  Bottom Diameter (IN): 2.0,  Top Diameter (IN): 3.1,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.1X4.0X2.0 IN, VB CUP COLD 10 OZ PET CLR 78 SERIES 20/50
- VGN: Carryout Bags, Inc.
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 10 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.0
- Top Diameter (IN): 3.1
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.1X4.0X2.0 IN
- Pattern & Design: VB CUP COLD 10 OZ PET CLR 78 SERIES 20/50
- Case Pack: 1000

- Entity ID: 18
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 20 OZ,  Bottom Diameter (IN): 2.3,  Top Diameter (IN): 3.9,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.9X5.4X2.3 IN, VB CUP COLD 20 OZ PET CLR 98 MM SERIES 20/50
- VGN: Carryout Bags, Inc.
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 20 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.3
- Top Diameter (IN): 3.9
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.9X5.4X2.3 IN
- Pattern & Design: VB CUP COLD 20 OZ PET CLR 98 MM SERIES 20/50
- Case Pack: 1000

- Entity ID: 61
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 600/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 24 OZ,  Bottom Diameter (IN): 2.4,  Top Diameter (IN): 3.9,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.9X5.9X2.4 IN, VB CUP COLD 24 OZ PET CLR 98 MM SERIES 12/50
- VGN: Carryout Bags, Inc.
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 24 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.4
- Top Diameter (IN): 3.9
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.9X5.9X2.4 IN
- Pattern & Design: VB CUP COLD 24 OZ PET CLR 98 MM SERIES 12/50
- Case Pack: 600

- Entity ID: 23
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 16 OZ,  Bottom Diameter (IN): 2.5,  Top Diameter (IN): 3.9,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.9X4.7X2.5 IN, VB CUP COLD 16 OZ PET CLR 98 MM SERIES 20/50
- VGN: Carryout Bags, Inc.
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 16 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.5
- Top Diameter (IN): 3.9
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.9X4.7X2.5 IN
- Pattern & Design: VB CUP COLD 16 OZ PET CLR 98 MM SERIES 20/50
- Case Pack: 1000

- Entity ID: 169
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 9 OZ,  Bottom Diameter (IN): 2.2,  Top Diameter (IN): 3.6,  Product Dimension Type: Tapered & Graduated Product Dimensions,  Product Dimensions: 3.6X2.8X2.2 IN, CUP COLD CLR PET PLASTIC 9 OZ SQUAT SOLO ULTRA 3.75 IN DIA
- VGN: Dart
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 9 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN): 2.2
- Top Diameter (IN): 3.6
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions: 3.6X2.8X2.2 IN
- Pattern & Design: CUP COLD CLR PET PLASTIC 9 OZ SQUAT SOLO ULTRA 3.75 IN DIA
- Case Pack: 1000

- Entity ID: 548
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Usage Temperature: Cold Only,  Product Capacity: 9 OZ, VB CUP COLD CLR PET 9 OZ TALL
- VGN: Direct Link
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes:
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 9 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN):
- Top Diameter (IN):
- Product Dimension Type:
- Product Dimensions:
- Pattern & Design: VB CUP COLD CLR PET 9 OZ TALL
- Case Pack: 1000

- Entity ID: 321
- Description: Beverage Cup Type: Cup,  Product Type Collapse: Cup,  Pack Size: 1000/Case,  Color: Clear,  Material: Polyethylene Terephthalate (PET),  Foodservice Global Attributes: Disposable,  Usage Temperature: Cold Only,  Product Capacity: 9 OZ,  Top Diameter (IN): 3.62,  Product Dimension Type: Tapered & Graduated Product Dimensions, C-KC9 9 OZ PET CLR CUP 20/50/CS
- VGN: Lollicup/Karat
- Beverage Cup Type: Cup
- Product Type Collapse: Cup
- Color: Clear
- Material: Polyethylene Terephthalate (PET)
- Foodservice Global Attributes: Disposable
- Usage Temperature: Cold Only
- Beverage Cup Style:
- Sustainable Products:
- Product Capacity: 9 OZ
- Compatible Product & Product Type:
- Bottom Diameter (IN):
- Top Diameter (IN): 3.62
- Product Dimension Type: Tapered & Graduated Product Dimensions
- Product Dimensions:
- Pattern & Design: C-KC9 9 OZ PET CLR CUP 20/50/CS
- Case Pack: 1000

- Entity ID: 137
- Description: VB CUP COLD 7 OZ CLR PET 78MM SERIES 20/50

In [11]:
print(len(user_prompts))

1653

In [12]:
im_final = mf.generate_matches(im_final, user_prompts, idx_map, batch_model = False)

[autoreload of Matching_functions failed: Traceback (most recent call last):
  File "C:\Users\MGadupudi\PycharmProjects\ImperialDadeCategoryManagement\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\MGadupudi\PycharmProjects\ImperialDadeCategoryManagement\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 475, in superreload
    module = reload(module)
  File "C:\Users\MGadupudi\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\MGadupudi\PycharmProjects\ImperialDadeCategoryManagement\Function_Files\Matching_functions.py", line 1121
    """Initialize 'Matches' and 'reasoning' columns if they don't exist."""
                                                               ^
SyntaxError: unterminated string literal (detected at line 1121)
]

Initializing OpenAI agent with model: gpt-4.1
Getting responses from API (batch=False)...

Running cost $10.0237: 100%|██████████| 52/52 [06:07<00:00,  7.07s/chunk]

Received 1653 responses
Responses: ['{\n  "Entity ID": 1,\n  "Matches": [16, 1357, 522],\n  "reasoning": "The original item is a 16 OZ hot cup lid made of polystyrene (PS), with a dome shape, black color, and sustainable attributes. The critical matching requirements (Product Capacity: 16 OZ, Beverage Cup Type: Lid, Usage Temperature: Hot Only) are met by Entity IDs 16, 1357, and 522. All three are Victoria Bay branded (VB) lids, match the capacity, type, and temperature, and are made of the same material. Directional attributes such as color (black or white), pack size, compatible cup size, and product dimension type are similar or identical. Other items either do not match the critical capacity requirement or lack sufficient information. The matches are ordered by vendor hierarchy, with Victoria Bay products listed first."\n}', '{\n  "Entity ID": 2,\n  "Matches": [\n    169,\n    548,\n    321,\n    661,\n    1068,\n    916\n  ],\n  "reasoning": "The original item is a 9 oz clear PET cold cup. The critical matching requirements are: Product Capacity (9 oz), Beverage Cup Type (Cup), and Usage Temperature (Cold Only). Only items with these exact values were considered. Directional attributes such as color, material, and product dimensions were also reviewed for similarity. The matches include Dart, Direct Link, Lollicup/Karat, and Pactiv products, all of which are preferred vendors for plastic cold cups. All matched items are clear PET cups for cold use with a 9 oz capacity. Victoria Bay branded items were not present in the similar items list for 9 oz capacity, so the matches are ordered by preferred vendor hierarchy. Items with different capacities (e.g., 10 oz, 12 oz, 7 oz, etc.) or different cup types (e.g., lid) were excluded."\n}', '{\n  "Entity ID": 3,\n  "Matches": [800, 849, 793, 436],\n  "reasoning": "All similar items have the same critical attributes as the original item: Beverage Cup Type (Beverage Plug), Product Type Collapse (Beverage Plug), and Pack Size (2000/Case). Usage Temperature is not specified for any item, so it is not a disqualifier. Directional attributes such as Material (Plastic), Foodservice Global Attributes (Disposable), and Compatible Product & Product Type (Hot Cup Lid) are also matching or similar. The only differences are in color and minor pattern/description details, which are acceptable per the guidelines. None of the items are Victoria Bay or preferred vendor brands, so all are listed under \'Others\' in the order provided."\n}']
Error: Response 14 is not a string. Type: BadRequestError
Error: Response 29 is not a string. Type: BadRequestError
Error: Response 90 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 100. Skipping.
Error: Response 189 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 210. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 221. Skipping.
Error: Response 329 is not a string. Type: BadRequestError
Error: Response 355 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 411. Skipping.
Error: Response 446 is not a string. Type: BadRequestError
Error: Response 468 is not a string. Type: BadRequestError
Error: Response 474 is not a string. Type: BadRequestError
Error: Response 477 is not a string. Type: BadRequestError
Error: Response 488 is not a string. Type: BadRequestError
Error: Response 493 is not a string. Type: BadRequestError
Error: Response 532 is not a string. Type: BadRequestError
Error: Response 556 is not a string. Type: BadRequestError
Error: Response 575 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 626. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 651. Skipping.
Error: Response 691 is not a string. Type: BadRequestError
Error: Response 727 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 754. Skipping.
Error: Response 837 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 871. Skipping.
Error: Response 873 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 887. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 890. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 951. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 955. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 964. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 976. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 997. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 999. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1001. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1005. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1006. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1013. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1019. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1024. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1025. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1027. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1029. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1030. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1032. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1033. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1039. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1042. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1049. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1050. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1053. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1054. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1073. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1081. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1082. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1083. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1091. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1094. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1095. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1115. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1120. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1121. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1134. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1140. Skipping.
Error: Response 1143 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 1149. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1150. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1152. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1153. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1154. Skipping.
Error: Response 1165 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 1169. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1173. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1194. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1198. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1201. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1202. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1203. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1204. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1205. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1207. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1208. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1209. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1210. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1213. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1215. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1233. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1252. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1259. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1268. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1301. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1326. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1327. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1351. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1353. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1359. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1365. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1379. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1382. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1388. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1402. Skipping.
Error: Response 1405 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 1419. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1429. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1436. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1441. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1449. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1454. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1474. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1499. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1501. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1502. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1503. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1504. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1505. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1506. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1512. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1514. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1515. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1519. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1520. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1521. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1522. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1523. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1524. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1526. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1530. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1534. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1535. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1538. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1540. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1542. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1549. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1552. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1553. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1559. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1561. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1566. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1567. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1584. Skipping.
Error: Response 1586 is not a string. Type: BadRequestError
Warning: Invalid or missing 'Entity ID' in AI response index 1592. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1600. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1605. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1610. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1613. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1620. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1628. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1629. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1632. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1634. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1636. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1638. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1640. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1641. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1643. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1645. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1647. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1650. Skipping.
Warning: Invalid or missing 'Entity ID' in AI response index 1652. Skipping.
Finished processing matches.

In [13]:
im_final.head()

,Entity--Item,Item Desc 1,Item Desc 2,Qty,Gross Cost,Net Cost,po_cost_amt,VB Flag,VGN,VPN,...,Bottom Diameter (IN),Top Diameter (IN),Product Dimension Type,Product Dimensions,Pattern & Design,Case Pack,for_embedding,embeddings,Matches,reasoning
0,1--VBCLLH16DB,VB LID HOT CUP DOME BLK 92MM,PS 10 OZ SQUAT-24 OZ 20/50,10474,185100,185880,20.629195,Y - VB,Graphic Packaging,316873008,...,NaN,92MM,Standard Product Dimensions,NaN,VB LID HOT CUP DOME BLK 92MM PS 10 OZ SQUAT-24...,1000,Lid Lid Black Polystyrene (PS) Hot Only Yes ...,"[-0.008323983289301395, 0.016245974227786064, ...","[1--VBCLLH16DW, 1--VBCLLH16FB, 1--VBCLLH16FW]",The original item is a 16 OZ hot cup lid made ...
1,1--PTC09D92,VB CUP COLD 9 OZ SQUAT PET,92 SERIES CLR 20/50,15365,487038,339648,43.747324,Y - VB,"Carryout Bags, Inc.",VB-VG9OF,...,2.4,3.6,Tapered & Graduated Product Dimensions,3.6X2.8X2.4 IN,VB CUP COLD 9 OZ SQUAT PET 92 SERIES CLR 20/50,1000,Cup Cup Clear Polyethylene Terephthalate (PET)...,"[-0.02888156846165657, 0.028642995283007622, -...","[1--TP9, 1--VBCLCPET9TC, 1--CKC9CUP, 1--TP9D, ...",The original item is a 9 oz clear PET cold cup...
2,1--CPLUGBLACK,PLUG CIRCLE BLK FOR HOT CUP,LID SIP HOLE 5/400 BLACK,1507,37845,37845,24.190000,N,Amercareroyal,CPLUG-BK,...,NaN,NaN,NaN,NaN,PLUG CIRCLE BLK FOR HOT CUP LID SIP HOLE 5/400...,2000,Beverage Plug Beverage Plug 2000/Case Black Pl...,"[-0.0005539848352782428, -0.004044089466333389...","[1--CPLUG, 1--CPLUG0, 1--CPLUGGREEN, 1--CPLUGW]",All similar items have the same critical attri...
3,1--2CUPCARRY,CARRIER HOLDER FOR 2 CUP,MOLDED FIBER 8-24 OZ,247,8645,8645,36.050000,Y - Other,"Carryout Bags, Inc.",2CUPCARRY,...,NaN,NaN,NaN,NaN,NaN,6000,Cup Carrier Without Tray Molded Fiber 8-2...,"[-0.006714086513966322, 0.02708226628601551, -...",[],None of the similar items provided meet all th...
4,1--DLKC12/20NH,LID CUP COLD DOME CLR PET,W/ NO HOLE KAL-CLR,412,27053,15549,70.922743,N,Pactiv,000000000009508059,...,NaN,NaN,Standard Product Dimensions,3.8X1.6 IN,LID CUP COLD DOME CLR PET W/ NO HOLE KAL-CLR,1000,Lid Lid Clear Polyethylene Terephthalate (PET)...,"[-0.02185988612473011, 0.006927075330168009, -...","[1--626NSL, 1--DLKC16/24NH, 1--LKC12/20F, 1--L...",The critical attributes for the original item ...

In [14]:
im_final['VB Flag'].unique()

array(['Y - VB', 'N', 'Y - Other'], dtype=object)

#### Write Matches Data

In [36]:
im_final.to_csv(f"{OP_PATH}{CATEGORY}_matches_non_printed.csv", index=False)

In [37]:
im_final = pd.read_csv(f"{OP_PATH}{CATEGORY}_matches.csv")

#### Output Subs report

In [16]:
mf.write_top_matches(im_final, f"{OP_PATH}{CATEGORY}_Subs_{today}.xlsx", n = 40, pl = True, enable_vpn_exclusion = True)

Starting write_top_matches with enable_vpn_exclusion=True
Looking for qty column: 'Qty'
Available columns: ['Entity--Item', 'Item Desc 1', 'Item Desc 2', 'Qty', 'Gross Cost', 'Net Cost', 'po_cost_amt', 'VB Flag', 'VGN', 'VPN', 'Pack Size', 'Combined Descriptions', 'Description with Attributes', 'attributes', 'Beverage Cup Type', 'Product Type Collapse', 'Color', 'Material', 'Foodservice Global Attributes', 'Usage Temperature', 'Beverage Cup Style', 'Sustainable Products', 'Product Capacity', 'Compatible Product & Product Type', 'Bottom Diameter (IN)', 'Top Diameter (IN)', 'Product Dimension Type', 'Product Dimensions', 'Pattern & Design', 'Case Pack', 'for_embedding', 'embeddings', 'Matches', 'reasoning', 'description_display_col']
Found qty column 'Qty' with 1653 rows
Qty column is numeric, sorting by Qty
Non-VB filter applied (VB Flag == 'N'): 1468 of 1653 rows qualify as targets
Selected top 40 non-VB items by Qty
Skipping target item: 1--8J8 — no valid substitutes found
Processed target item: 1--16J16 with 1 substitutes
Processed target item: 1--16SL with 2 substitutes
Processed target item: 1--12J12 with 3 substitutes
Processed target item: 1--20JL with 3 substitutes
Processed target item: 1--626NSL with 14 substitutes
Skipping target item: 1--6J6 — no valid substitutes found
Processed target item: 1--20J16 with 4 substitutes
Processed target item: 1--626XS with 2 substitutes
Processed target item: 1--32SL1 with 1 substitutes
Processed target item: 1--20SL with 1 substitutes
Processed target item: 1--9508082 with 4 substitutes
Processed target item: 1--6L with 3 substitutes
Skipping target item: 1--10J10 — no valid substitutes found
Skipping target item: 1--45UNIPAK — no valid substitutes found
Processed target item: 1--12J16 with 3 substitutes
Processed target item: 1--Y12S with 3 substitutes
Processed target item: 1--LK316W with 15 substitutes
Processed target item: 1--TLP316 with 5 substitutes
Processed target item: 1--32TJ32 with 2 substitutes
Processed target item: 1--12SJ20 with 1 substitutes
Processed target item: 1--16FTLS with 3 substitutes
Processed target item: 1--16MJ20 with 4 substitutes
Processed target item: 1--9509106 with 2 substitutes
Processed target item: 1--18212 with 4 substitutes
Processed target item: 1--L32C with 13 substitutes
Processed target item: 1--LGC16/24 with 4 substitutes
Processed target item: 1--9509104 with 3 substitutes
Processed target item: 1--18202 with 5 substitutes
Processed target item: 1--9509100 with 4 substitutes
Processed target item: 1--9501111 with 13 substitutes
Processed target item: 1--20994 with 3 substitutes
Processed target item: 1--LHRDS16 with 4 substitutes
Processed target item: 1--CKCL1045 with 4 substitutes
Processed target item: 1--24J16 with 1 substitutes
Processed target item: 1--LHRDSB16 with 9 substitutes
Skipping target item: 1--12JL — no valid substitutes found
Skipping target item: 1--4J4 — no valid substitutes found
Processed target item: 1--20990 with 1 substitutes
Skipping match 1--8HT due to VPN matching conditions
Processed target item: 1--LHRL8 with 6 substitutes
Excel report successfully created: C:\Users\MGadupudi\PycharmProjects\ImperialDadeCategoryManagement\Data\Cups\Output\Cups_Subs_04.16.2026.xlsx

In [5]:
im_final = pd.read_csv(f"{OP_PATH}{CATEGORY}_matches_non_printed.csv")

In [6]:
im_final.columns

Index(['Entity--Item', 'Item Desc 1', 'Item Desc 2', 'Qty', 'Gross Cost',
       'Net Cost', 'po_cost_amt', 'VB Flag', 'VGN', 'VPN', 'Pack Size',
       'Combined Descriptions', 'Description with Attributes', 'attributes',
       'Beverage Cup Type', 'Product Type Collapse', 'Color', 'Material',
       'Foodservice Global Attributes', 'Usage Temperature',
       'Beverage Cup Style', 'Sustainable Products', 'Product Capacity',
       'Capacity Value 1', 'Capacity Preferred Metric 1',
       'Lid, Cover & Cap Type', 'Lid, Cover & Cap Style',
       'Compatible Product & Product Type', 'Bottom Diameter (IN)',
       'Top Diameter (IN)', 'Product Dimension Type', 'Wall Height (IN)',
       'Product Dimensions', 'Case Pack', 'for_embedding', 'embeddings',
       'Matches', 'reasoning'],
      dtype='object')

In [32]:
im_final[['Entity--Item', 'Item Desc 1', 'Item Desc 2', 'Qty', 'Gross Cost',
       'Net Cost', 'po_cost_amt', 'VB Flag', 'VGN', 'VPN', 'Matches', 'reasoning']].to_csv(f"{OP_PATH}{CATEGORY}_matches_non_printed_Omar_extract.csv", index=False)